### PR TITLE
refactor ES configs to be portable

### PR DESCRIPTION
**Pull request by HerbFargus**
This is just an initial pass at making the ES configs portable. This way people can run ES from a USB stick or an external harddrive etc. of course as these are just configs they'll either need to download the release with the binaries (which is going to be the recommended route) or manually copy the ES binaries into the proper paths. 

Summary of changes:
- I've moved a bunch of stuff around so it is portable, it more closely matches the layout of the release binaries (currently posted as a draft til we sort the master to maintain parity) and also my portable game station build.
- moved images and gamelists (also modified gamelists to new path) within rom folders. placed images in media folder, though I'm thinking we may want to split it further into folders for images/videos/marquees etc.
- For the binary release I included the videos in the rom folders, but for people manually adding the videos, they'll have to add them to the new locations in the roms folders
- added a new launch bat called fullscreen. it will launch a full screen ES not in a window based on the res of the machine it is running but its important to note that 4K displays do not work, so people will need to use a windowed launch bat if thats the case. also being portable the regular exe will not run, people are required to use one of the batch scripts.
- Added Rookerviks theme helper
- Added a stripped down version of the carbon theme (with video support) for the 5 systems listed. I've included the full carbon theme in the binary release

We'll probably have to update some of the readmes as well as they got shifted around. again this is just a rough first modification, and will require a bit of cleanup etc. 

Also in terms of the images and gamelists within rom folders, is there a mechanism for UXS to handle that or is it hardcoded to the downloaded_images / gamelist configuration? I know sselphs scraper in retropie has options to choose where the images and gamelists are scraped to.

as a note es_settings, es_input, es_log all shouldn't be part of the repo. those will be generated based on the initial boot of ES and I think we should leave it to the user to generate their preferred controls.

As far as the helpers and extra tools I wonder if we should only include them in binaries and just keep this repo as a config specifically for emulationstation?

### CODE REVIEW

**Comment by HerbFargus** [comment]
Just checking what's the status on this? (I also need to update my binary with the latest carousel changes)

**Comment by mattrixk** [comment]
I'm sorry Herb, I've had no time to myself at all this weekend, it's
currently Sunday night, 7:30pm, the neighbours have just left after coming
over for dinner and my toddler is freshly bathed. Once he's down I'll have
to spend some time with the missus, and then probably head to bed. If I
stay up for a bit I can have a bit of a look tonight, but it's probably
going to be tomorrow during my lunch break at the earliest.

What exactly do you need from me for this? Will I have to approve something
within github to merge the branches or something? I'm still quite new to
git.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by HerbFargus** [comment]
No worries, take all the time you need for family first. This is hardly a priority ;) 

If/when you're happy with the changes you can click the green merge button. 

I know you said you had some modifications to make with your mix profiles, and once it's merged there will be some minor cleanups with the readmes which I can help update along with the binary release. 

Once we are happy we can push out a 1.1 release and in theory people will be able to download the binary, extract it on a USB and be up and running immediately.

**Comment by mattrixk** [comment]
> Once we are happy we can push out a 1.1 release and in theory people will
be able to download the binary, extract it on a USB and be up and running
immediately.

That sounds great. I like the idea of an all-in-one package.

I noticed that Zigurana's Carousel Mod has been accepted into the core. Is
that part of your latest build?

**Comment by HerbFargus** [comment]
It isn't in the binary yet but I will swap it out and upload the binary before we publish a release

**Comment by HerbFargus** [comment]
I'm not sure how custom your profiles are with UXS, especially compared to the latest release. I wonder if there may just be merit to including UXS with the binary release and letting users configure their paths and layouts. I haven't really used it so I'm not sure how extensive it is with its latest update.

**Comment by HerbFargus** [comment]
I've made an update to the draft with the latest ES binary with carousel support

**Comment by mattrixk** [comment]
*A word of warning, this may get long.*

So I've finally had a chance to really go through your first post here, so I'll answer a question and then ask a few of my own.

> in terms of the images and gamelists within rom folders, is there a mechanism for UXS to handle that or is it hardcoded to the downloaded_images / gamelist configuration?

Within the standalone UXS program you can choose your path configuration, so you can set it to download the images to the Roms folder and point the gamelist to the correct place. It updates the Scrape Profile you are using to reflect this. I'm not sure about being able to save the gamelist to the Rom folder, I'll have to look into that.

*strange, when I was reading through the first time I thought there were more questions to answer, but now it comes to writing down answers I only found one question.*

---

Now, I need some clarifications as I'm easliy confused.

**What do you mean by "configs" and "binaries"?**

You mentioned "making the ES configs portable", are you refering to something within the "emulationstation.exe", to specific files within the Root EmulationStation folder (like the .dll or .lib files), or to files like es_systems.cfg and es_settings.cfg within the ".emulationstation" folder?

When you talk about "binaries" are you referring to just the "emulationstation.exe", the ES program as a whole (including .cfg files, themes, fake roms, media, launch .bats, retroarch files, etc), or to the Base ES program minus all the fake roms and such?

---

Here is what I think are the various parts of the Toolkit (that we can then mix and match to make various releases to suit different purposes). Let me know if I've missed anything:

- Latest build of ES that includes Video Preview, `<featured>` tags, Carousel Mod.
- Launch Bats
- Fake Roms
- Scraped Images
- Scraped Videos
- Gamelists: Pre-filled for the Fake Roms
- Video-enabled Themes
- UXS Scrape and MIX Profiles
- Rookervik's Theme Helper
- es_systems.cfg (I understand not needing es_settings, es_input and es_log in the Repo)
- Retroarch: to make ES usable to actually play games (can we have some cores already available or does it have to be empty?)

---

Here are the different releases that I think would be good to have:

- A Full Version:
  - This version would have a full Portable ES with all of the elements listed above in it. A user can download it and go straight into theme making, or load up some Roms, download some RetroArch Cores and play some games.

- A Theme Making Version:
  - This version would be the same as the full version, only it wouldn't have the RetroArch files so it would dramatically reduce the file size.

- A Game Playing Version:
  - This version would be a clean Portable ES with RetroArch, but it would be missing all the fake Roms, all the scraped media and gamelists, all the UXS profiles, and the Theme Helper. It would just be so a user could download it, add some Roms and RetroArch Cores and start playing.

- The Toolkit without ES:
  - As it says, this is just the Toolkit minus any build of ES. It's basically the version that's already in the Repo, except with your changes to the Media placement, the addition of the Theme Helper and such.

---

Now, on to your Game Station 1.5.

When I first started it I got the "we can't find any systems" message even though you have some ports in the Ports folder. I'm guessing it didn't find them because even though you have the .bat files, the folders were empty (but for a text file).

I added the Roms folder from the refactored Toolkit and added the videos from Video Toolkit and it all worked without a problem. I had to make a little change to the Carbon theme to get it to put the `<marquee>` in the correct place, but that's because I'm using the MIX image as the marquee.

I think we need to change the gamelists to use the Logo as the marquee instead of the MIX image, as that seems like it would be what most people would use as the marquee

---

Yeah, that did get a bit long didn't it?

**Comment by HerbFargus** [comment]
When I refer to binaries I mean the executable files that we only include in the release:

emulationstation.exe and perhaps UXS (though I may defer to the users to install that as it seems to change somewhat frequently and they may be using older versions)

As far as releases go- this being the ES toolkit it seems a bit overkill to release variant binary releases for different needs. I presumed this was designed primarily as a help for theme making.

I envision 2 methods:

1. **Manual Installation** - this is where a user just clones the repo and adds their own ES binary and/or copies the dummy roms/configs to their own systems
2. **Binary Installation** - The user downloads the binary release from the releases page and can extract it onto a USB stick and be immediately up and running complete with latest ES, dummy roms, gamelists, and images and videos,

As far as integrating retroarch we should just defer them to my portable game station for that if thats really what they are looking for as the 1.5 release has the ES with video support now. no sense in duplicating efforts for something that already exists.

**Comment by mattrixk** [comment]
I merged the 2, I hope I did it right. I thought it would add your files to mine, but it's just kind of removed mine and put yours in it's place (I don't mind it doing that, I just didn't know that's what would happen).

**Comment by HerbFargus** [comment]
a lot of things moved around, so there will be a bit of cleanup primarily with the readmes, but i feel like its cleaner now as far as being portable.

eg if someone wants to add the dummy roms to their system all they have to do is copy over the roms folder, instead of having to copy over a bunch of folders and files in different places.

**Comment by mattrixk** [comment]
> but i feel like its cleaner now [...] if someone wants to add the dummy roms to their system all they have to do is copy over the roms folder, instead of having to copy over a bunch of folders and files in different places.

Agreed.

I'll clean up the readme files, change the gamelists to point at the Logo instead of the Mix image and fix up the `<size>`/`<maxSize>` and `<pos>` elements in both Carbon and BaseVid to reflect this change

**Comment by HerbFargus** [comment]
I've got a bit of a start on the main readme just as a quick howto for downloading/ installation:

I'll submit a PR for review. I'd like to keep it as brief as we can and then maybe we can add a few wiki pages on building ES on retropie etc.

**Pull request merged**
